export class LookupConfiguration{
    id:number=0;
    type:string='';
    lookupName:string='';
    lookupLink:string='';
    addedBy:string='';
    planIds:string='';
    version:string='';
    taxonomyId:any;
    lastTestedOn:any;
    reportStatus:string='';
    url:any;
    attachmentType:string='';
    attachmentSubType:string='';
    updatedDate:any;
    configStatus:string='';
    toggle:boolean=false;
    ticketType:string='';
}